title: "GitHub Actions: Writing JavaScript Actions"
description: >-
  Learn how to write your own GitHub JavaScript Action!  This course will
  empower you to begin automating customized tasks unique to your workflow.
template:
  repo: "writing-javascript-actions-template"
  name: "writing-javascript-actions"

# Repo artifacts:
# 1. (Issue) Start here!
# 2. (PR) Create a workflow
# 3. (Issue) Your first JavaScript action
# 4. (PR) Hello action
# 5. (Issue) Knock Knock...
# 6. (PR) External APIs
# 7. (Issue) Consuming Action Outputs
# 8. (PR) Use Outputs
# 9. (Issue) Last minute notes

before:
  - type: updateBranchProtection
  - type: createLabel
    name: first-joke
    color: FFBD33
  - type: createLabel
    name: second-joke
    color: 33FFBD
  - type: createLabel
    name: third-joke
    color: 3F8A99
  - type: createIssue
    title: Start here!
    body: 01_welcome-activity.md
    data:                                          
      quicklink: "%payload.repository.html_url%/new/master?filename=.github/workflows/my-workflow.yml&workflow_template=blank"
      actionsUrl: "%payload.repository.html_url%/actions/new"
steps:
  - title: Setup a workflow file
    description: Create a pull request to add a workflow
    event: 
        # if the payload action is 'opened' OR 'edited'
      - pull_request.opened
      - pull_request.edited
      - pull_request.synchronize
    link: "{{ repoUrl }}/issues/1"
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: Create a workflow

        # if those statments FAIL... do this
        else:
          - type: respond
            with: e-rename-pr.md
            data:
              title: Create a workflow
          # if those gates === true Then do this stuff

      - type: closeIssue
        issue: Start here!

      - type: getFileContents
        filename: '.github/workflows/my-workflow.yml'
        action_id: workflowFileContents
        required: false

      - type: gate
        left: '%actions.workflowFileContents%'
        else:
          - type: respond
            with: e-404.md
            data:
              need: .github/workflows/my-workflow.yml

      - type: respond
        with: 01_explain-workflow.md
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: respond
        with: 01_explain-environment.md
      - type: respond
        with: 01_explain-syntax.md

  - title: Run a workflow
    description: Wait for GitHub to run the workflow and report back the results
    event: check_suite.completed
    link: "{{ repoUrl }}/pull/2"
    actions:
      - type: gate
        left: "%payload.check_suite.app.name%"
        operator: ===
        right: "GitHub Actions"
        else:
          - type: respond
            issue: Create a workflow
            with: debug.md
            data:
              debug: '%payload%'
      - type: respond
        with: 02_workflow-results.md
        issue: Create a workflow
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: getPullRequest
        pullRequest: Create a workflow
        action_id: iwPr
      - type: respond
        with: 02_modify-workflow.md
        issue: Create a workflow
        data:
          workflowFile: "%payload.repository.html_url%/edit/%actions.iwPr.data.head.ref%/.github/workflows/my-workflow.yml?pr=/%actions.iwPr.data.base.repo.full_name%/pull/%actions.iwPr.data.number%"

  - title: Prep the workflow
    description: Prepare the workflow for your future action
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pull/2"
    actions:
      # Make sure we have the right PR
      - type: gate
        left: '%payload.pull_request.title%'
        operator: ===
        right: Create a workflow

      - type: getFileContents
        filename: '.github/workflows/my-workflow.yml'
        action_id: workflowFileContents
        required: false

      - type: gate
        left: '%actions.workflowFileContents%'
        else:
          - type: respond
            with: e-404.md
            data:
              need: .github/workflows/my-workflow.yml

      - type: gate
        left: '/name:\s*JS Actions/gm'
        operator: test
        right: '%actions.workflowFileContents%'
        else:
          - type: respond
            with: e-line.md
            data:
              filename: .github/workflows/my-workflow.yml
              code: 'name: JS Actions'
              got: '%actions.workflowFileContents%'

      - type: gate
        left: '/uses:\s*actions\/checkout@v1\n*$/g'
        operator: test
        right: '%actions.workflowFileContents%'
        else:
          - type: respond
            with: e-end.md
            data:
              filename: .github/workflows/my-workflow.yml
              code: '- uses: actions\/checkout@v1'
              got: '%actions.workflowFileContents%'

      - type: gate
        left: '/action:/gm'
        operator: test
        right: '%actions.workflowFileContents%'
        else:
          - type: respond
            with: e-line.md
            data:
              filename: .github/workflows/my-workflow.yml
              code: 'action:'

      - type: getPullRequest
        pullRequest: Create a workflow
        action_id: workflowPr
      - type: respond
        with: 03_reference-actions.md
        data:
          workflowFile: "%payload.repository.html_url%/edit/%actions.workflowPr.data.head.ref%/.github/workflows/my-workflow.yml?pr=/%actions.workflowPr.data.base.repo.full_name%/pull/%actions.workflowPr.data.number%"

  - title: Add an Action reference
    description: Add an Action reference to the workflow file
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pull/2"
    actions:
      - type: getFileContents
        filename: '.github/workflows/my-workflow.yml'
        action_id: workflowFileContents
        required: false

      - type: gate
        every: true
        gates:
        - left: '/name:\s*hello-action/gm'
          operator: test
          right: '%actions.workflowFileContents%'
        - left: '/uses:\s*\.\/\.github\/actions\/hello-world/gm'
          operator: test
          right: '%actions.workflowFileContents%'
        else:
          - type: respond
            with: e-line.md
            data:
              filename: .github/workflows/my-workflow.yml
              code: |
                - name: hello-action
                  uses: ./.github/actions/hello-world
              got: '%actions.workflowFileContents%'

      - type: createIssue
        title: Your first JavaScript action
        body: dev-env.md
        action_id: devEnv
      - type: createReview
        event: APPROVE
        body: 04_on-to-actions.md
        data:
          issueUrl: "%actions.devEnv.data.html_url%"
        pullRequest: Create a workflow
      - type: mergePullRequest

  - title: On to your development environment
    description: Lets prepare your environment to start writing Actions
    event: push
    link: "{{ repoUrl }}/issues/3"
    actions:
      - type: gate
        left: "%payload.ref%"
        operator: ===
        right: "refs/heads/hello-world"
        else:
        - type: respond
          issue: Your first JavaScript action
          with: e-branch.md
          data: 
            expected: hello-world

      - type: getFileContents
        filename: '.github/actions/hello-world/package.json'
        action_id: packageJSON
        required: false

      - type: gate
        left: '/@actions\/core/gm'
        operator: test
        right: '%actions.packageJSON%'
        else:
          - type: respond
            with: e-actions-dep.md
            issue: Your first JavaScript action

      - type: createPullRequest
        title: Hello action
        body: 05_explain-actions.md
        head: hello-world
        action_id: helloPr
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: respond
        with: 05_hello-pr.md
        issue: Your first JavaScript action
        data:
          pullUrl: "%actions.helloPr.data.html_url%"
      - type: closeIssue
        issue: Your first JavaScript action
      - type: respond
        with: 05_explain-metadata.md
        issue: Hello action
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: respond
        with: 05_create-metadata.md
        issue: Hello action

  - title: Creating the Action metadata
    description: Create an action.yml file and add necessary metatdata for our Action
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pull/4"
    actions:
      - type: gate
        left: '%payload.pull_request.title%'
        operator: ===
        right: Hello action
        else:
          - type: respond
            with: e-unexpected.md
            data:
              expected: push a commit to the pull request titled "Hello action"

      - type: getFileContents
        filename: '.github/actions/hello-world/action.yml'
        action_id: actionYML
        required: false

      - type: gate
        left: '%actions.actionYML%'
        else:
          - type: respond
            with: e-404.md
            data:
              need: .github/actions/hello-world/action.yml

      - type: respond
        with: 06_explain-runs.md
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: respond
        with: 06_main-js.md
        data:
          actionsUrl: "%payload.repository.html_url%/actions"

  - title: Create the Action entrypoint
    description: Add code to main.js file
    event: pull_request.synchronize #ideally would like the workflow completing to tigger this
    link: "{{ repoUrl }}/pull/4"
    actions:
      - type: gate
        left: '%payload.pull_request.title%'
        operator: ===
        right: Hello action
        else:
          - type: respond
            with: e-unexpected.md
            data:
              expected: push a commit to the pull request titled "Hello action"

      - type: getFileContents
        filename: '.github/actions/hello-world/main.js'
        action_id: mainJS
        required: false

      - type: gate
        left: '%actions.mainJS%'
        else:
          - type: respond
            with: e-404.md
            data:
              need: .github/actions/hello-world/main.js

      - type: respond
        with: 07_hello-result.md
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: respond
        with: 07_add-input-params.md
      - type: respond
        with: 07_update-files.md

  - title: Exploring your input parameters
    description: View the results of adding input parameter
    event: check_suite.completed #ideally would like workflow complete to trigger this
    link: "{{ repoUrl }}/pull/4"
    actions:
      - type: gate
        every: true
        gates:
          - left: "%payload.check_suite.app.name%"
            operator: ===
            right: "GitHub Actions"
          - left: "%payload.check_suite.conclusion%"
            operator: ===
            right: success

      - type: respond
        with: 08_input-result.md
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: removeBranchProtection
      - type: respond
        with: 08_experiment.md

  - title: Integrating Actions with external APIs
    description: Write a new Action that calls an external API
    event: pull_request.closed
    link: "{{ repoUrl }}/pull/4"
    actions:
      - type: updateBranchProtection
      - type: createIssue
        body: 09_joking-around.md
        title: Knock Knock...
        action_id: jokeIssue
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: respond
        with: 08_next-steps.md
        issue: Hello action
        data:
          issueUrl: "%actions.jokeIssue.data.html_url%"
      - type: respond
        with: 09_new-action.md
        issue: Knock Knock...
        data:
          # The following workflowFile var does not point where it should for some reason
          workflowFile: "%payload.repository.html_url%/edit/master/.github/workflows/my-workflow.yml"
          actionsUrl: "%payload.repository.html_url%/actions"

  - title: Prevent the workflow from running
    description: Comment out the lines in the workflow to prevent unwanted runs
    event: 
      - pull_request.opened
      - pull_request.edited
    link: "{{ repoUrl }}/issues/5"
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: External APIs

        # if those statments FAIL... do this
        else:
          - type: respond
            with: e-rename-pr.md
            data:
              title: External APIs
          # if those gates === true Then do this stuff

      - type: getFileContents
        filename: '.github/workflows/my-workflow.yml'
        action_id: workflow
        required: false

      - type: gate
        left: '%actions.workflow%'
        else:
          - type: respond
            with: e-404.md
            data:
              need: .github/workflows/my-workflow.yml
              
      - type: closeIssue
        issue: Knock Knock...
      - type: respond
        with: 10_action-two.md

  - title: Create your new Action metadata
    description: Add action.yml file for new joke action
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pull/6"
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: External APIs
      - type: respond
        with: 10_create-metadata.md

  - title: Create your Actions JavaScript files
    description: Add joke.j and main.js to your Action
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pull/6"
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: External APIs
      - type: respond
        with: 10_create-js-files.md

  - title: Use the joke Action in a workflow
    description: Edit the workflow file to now use the newly created joke Action
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pull/6"
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: External APIs
      - type: getPullRequest
        pullRequest: External APIs
        action_id: apiPr
      - type: respond
        with: 11_edit-workflow.md
        data:
          workflowFile: "%payload.repository.html_url%/edit/%actions.apiPr.data.head.ref%/.github/workflows/my-workflow.yml?pr=/%actions.apiPr.data.base.repo.full_name%/pull/%actions.apiPr.data.number%"
          actionsUrl: "%payload.repository.html_url%/actions"

  - title: Having Actions tell a joke... or two
    description: Wait for your Action to present you with a joke
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pull/6"
    actions:
      - type: removeBranchProtection
      - type: respond
        with: 12_trigger-workflow.md
        issue: External APIs
        data:
          actionsUrl: "%payload.repository.html_url%/actions"

  - title: Configure the workflow for a third Action
    description: Edit the workflow to accomodate the third action
    event: pull_request.closed
    link: "{{ repoUrl }}/pull/6"
    actions:
      - type: updateBranchProtection
      - type: createIssue
        body: 13_action-three-workflow.md
        title: Consuming Action Outputs
        action_id: outputIssue
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
          workflowFile: "%payload.repository.html_url%/edit/master/.github/workflows/my-workflow.yml"
      - type: respond
        with: 12_next-steps.md
        issue: External APIs
        data:
          issueUrl: "%actions.outputIssue.data.html_url%"

  - title: Write the final Action
    description: Create an Action that consumes output from another Action and uses Octokit
    event: pull_request
    link: "{{ repoUrl }}/issues/7"
    actions:
      - type: gate
        gates:
          # if the payload action is 'opened' OR 'edited'
          - left: "%payload.action%"
            operator: ===
            right: opened
          - left: "%payload.action%"
            operator: ===
            right: edited
            # AND the pull request title equals 'Create a workflow'
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: Use Outputs

        # if those statments FAIL... do this
        else:
          - type: respond
            with: e-rename-pr.md
            data:
              title: Use Outputs
          # if those gates === true Then do this stuff
      - type: closeIssue
        issue: Consuming Action Outputs
      - type: respond
        with: 14_action-three.md

  - title: Add third Actions metadata
    description: Create the metadata for the third Action
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pull/8"
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: Use Outputs
      - type: respond
        with: 14_create-metadata.md

  - title: Add third Actions JavaScript files
    description: Create the JavaScript files for the third Action
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pull/8"
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: Use Outputs
      - type: respond
        with: 14_create-js-files.md
      - type: respond
        with: 14_js-files-activity.md

  - title: Trigger the third Action
    description: Add a pull request label to trigger the workflow
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pull/8"
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: Use Outputs
      - type: removeBranchProtection
      - type: respond
        with: 15_add-a-label.md
        data:
          actionsUrl: "%payload.repository.html_url%/actions"

  - title: Wrapping things up
    description: Final notes before you go
    event: pull_request.closed
    link: "{{ repoUrl }}/pull/8"
    actions:
      - type: createIssue
        title: Last minute notes
        body: great-job.md
        comments:
          - 16_using-ncc.md
          - 16_publishing.md
          - 16_complete.md
        action_id: finalIssue
      - type: respond
        with: go-to-final.md
        data:
          url: '%actions.finalIssue.data.html_url%'

tags: [
  "JavaScript", "API", "Actions toolkit", "GitHub Secrets", "Workflows"
]