title: "GitHub Actions: Writing JavaScript Actions"
tagline: Create custom automation tasks for your unique workflow using GitHub Actions
description: >-
  Learn how to write your own GitHub JavaScript Action!  This course will
  empower you to begin automating customized tasks unique to your workflow.
template:
  repo: "writing-javascript-actions-template"
  name: "writing-javascript-actions"
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Start Here!
    body: welcome-issue.md
    data:
      actionsUrl: "%payload.repository.html_url%/actions/new"
steps:
  - title: Prepare the repository
    description: Create a pull request to add a workflow
    event: pull_request
    link: "{{ repoUrl }}/issue1/1"
    actions:
      - type: gate
        gates:
          # if the payload action is 'opened' OR 'edited'
          - left: "%payload.action%"
            operator: ===
            right: opened
          - left: "%payload.action%"
            operator: ===
            right: edited
            # AND the pull request title equals 'Initial Workflow'
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: Initial Workflow

        # if those statments FAIL... do this
        else:
          - type: respond
            with: e-rename-pr.md
            data:
              title: Initial Workflow
          # if those gates === true Then do this stuff
      - type: closeIssue
        issue: Start Here!
      - type: respond
        with: 01_explain-workflow.md
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: respond
        with: 01_explain-environment.md
      - type: respond
        with: 01_explain-syntax.md

  - title: Run a workflow
    description: Wait for GitHub to run the workflow and report back the results
    event: check_suite.completed
    link: "{{ repoUrl }}/pull/2"
    actions:
      - type: gate
        left: "%payload.check_suite.app.name%"
        operator: ===
        right: "GitHub Actions"
      - type: respond
        with: 02_workflow-results.md
        issue: Initial Workflow
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: getPullRequest
        pullRequest: Initial Workflow
        action_id: iwPr
      - type: respond
        with: 02_modify-workflow.md
        issue: Initial Workflow
        data:
          workflowFile: "%payload.repository.html_url%/edit/%actions.iwPr.data.head.ref%/.github/workflows/my-workflow.yml"

  - title: Add an Action reference
    description: Add an Action reference to the workflow file
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pull/2"
    actions:
      - type: getPullRequest
        pullRequest: Initial Workflow
        action_id: workflowPr
      - type: respond
        with: 03_reference-actions.md
        data:
          workflowFile: "%payload.repository.html_url%/edit/%actions.workflowPr.data.head.ref%/.github/workflows/my-workflow.yml"

  - title: On to your development environment
    description: Lets prepare your environemtn to start writing Actions
    event: pull_request.synchronize
    actions:
      - type: createIssue
        title: Setting up your development environment
        body: dev-env.md
        action_id: devEnv
      - type: createReview
        event: APPROVE
        body: 04_on-to-actions.md
        data:
          issueUrl: "%actions.devEnv.data.html_url%"
        pullRequest: Initial Workflow
      - type: mergePullRequest

  - title: Creating the Action metadata
    description: Create an action.yml file and add necessary metatdata for our Action
    event: push
    # link: "{{ repoUrl }}/issue1/1"
    actions:
      - type: gate
        left: "%payload.ref%"
        operator: ===
        right: "refs/heads/hello-world"
      - type: gate
        left: "%payload.created%"
        operator: ===
        right: true
      - type: createPullRequest
        title: Hello Action
        body: 05_explain-metadata.md
        head: hello-world
        action_id: helloPr
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: respond
        with: 05_hello-pr.md
        issue: Setting up your development environment
        data:
          pullUrl: "%actions.helloPr.data.html_url%"
      - type: closeIssue
        issue: Setting up your development environment
      - type: respond
        with: 05_create-metadata.md
        issue: Hello Action

  - title: Create the Action entrypoint
    description: time to start adding code to main.js
    event: pull_request.synchronize
    actions:
      - type: respond
        with: 06_explain-runs.md
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: respond
        with: 06_main-js.md
        data:
          actionsUrl: "%payload.repository.html_url%/actions"

  - title: Adding input parameters
    description: extend your action to accept input parameters
    event: pull_request.synchronize #ideally would like the workflow completing to tigger this
    actions:
      - type: respond
        with: 07_hello-result.md
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: respond
        with: 07_add-input-params.md
      - type: respond
        with: 07_update-files.md

  - title: Exploring your input parameters
    description: view the results of adding input parameter
    event: pull_request.synchronize #ideally would like workflow complete to trigger this
    actions:
      - type: respond
        with: 08_input-result.md
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: removeBranchProtection
      - type: respond
        with: 08_experiment.md

  - title: Integrating Actions with external APIs
    description: Write a new Action that call an external API
    event: pull_request.closed
    actions:
      - type: updateBranchProtection
      - type: createIssue
        body: 09_joking-around.md
        title: Knock Knock...
        action_id: jokeIssue
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
      - type: respond
        with: 08_next-steps.md
        issue: Hello Action
        data:
          issueUrl: "%actions.jokeIssue.data.html_url%"
      - type: respond
        with: 09_new-action.md
        issue: Knock Knock...
        data:
          workflowFile: "%payload.repository.html_url%/edit/master/.github/workflows/my-workflow.yml"
          actionsUrl: "%payload.repository.html_url%/actions"

  - title: Prevent the workflow from running
    description: Comment out the lines in the workflow to prevent unwanted runs
    event: pull_request
    # link: "{{ repoUrl }}/issue1/1"
    actions:
      - type: gate
        gates:
          # if the payload action is 'opened' OR 'edited'
          - left: "%payload.action%"
            operator: ===
            right: opened
          - left: "%payload.action%"
            operator: ===
            right: edited
            # AND the pull request title equals 'Initial Workflow'
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: External APIs

        # if those statments FAIL... do this
        else:
          - type: respond
            with: e-rename-pr.md
            data:
              title: External APIs
          # if those gates === true Then do this stuff
      ###############################################################################################################
      - type: closeIssue
        issue: Knock Knock...
      - type: respond
        with: 10_action-two.md

  - title: Create your new Action metadata
    description: Add action.yml file for new joke action
    event: pull_request.synchronize
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: External APIs
      - type: respond
        with: 10_create-metadata.md

  - title: Create your Actions JavaScript files
    description: Add joke.j and main.js to your Action
    event: pull_request.synchronize
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: External APIs
      - type: respond
        with: 10_create-js-files.md

  - title: Use the joke Action in a workflow
    description: Edit the workflow file to now use the newly created joke Action
    event: pull_request.synchronize
    actions:
      - type: gate
        left: "%payload.pull_request.title%"
        operator: ===
        right: External APIs
      - type: getPullRequest
        pullRequest: External APIs
        action_id: apiPr
      - type: respond
        with: 11_edit-workflow.md
        data:
          workflowFile: "%payload.repository.html_url%/edit/%actions.apiPr.data.head.ref%/.github/workflows/my-workflow.yml"
          actionsUrl: "%payload.repository.html_url%/actions"

  - title: Having Actions tell a joke... or two
    description: Wait for your Action to present you with a joke
    event: pull_request.synchronize
    # link: "{{ repoUrl }}/pull/2"
    actions:
      - type: gate
        left: "%payload.check_suite.app.name%"
        operator: ===
        right: "GitHub Actions"
      - type: respond
        with: 12_trigger-workflow.md
        issue: External APIs
        data:
          actionsUrl: "%payload.repository.html_url%/actions"
